# Generated by Django 4.1 on 2022-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='chars',
            field=models.JSONField(default=1, verbose_name='characteristics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=1, verbose_name='description'),
            preserve_default=False,
        ),
    ]
